
const uint16_t cMajScaleSample[] = {
		MUSIC_COMMAND_SPEED | 120,
		MUSIC_COMMAND_VOLUME | MUSIC_TRACK_0 | 255,

		MUSIC_COMMAND_PLAY_NOTE | MUSIC_TRACK_0 | NOTE_C4,
		MUSIC_COMMAND_NEXT | 1,
		MUSIC_COMMAND_PLAY_NOTE | MUSIC_TRACK_0 | NOTE_D4,
		MUSIC_COMMAND_NEXT | 1,
		MUSIC_COMMAND_PLAY_NOTE | MUSIC_TRACK_0 | NOTE_E4,
		MUSIC_COMMAND_NEXT | 1,
		MUSIC_COMMAND_PLAY_NOTE | MUSIC_TRACK_0 | NOTE_F4,
		MUSIC_COMMAND_NEXT | 1,
		MUSIC_COMMAND_PLAY_NOTE | MUSIC_TRACK_0 | NOTE_G4,
		MUSIC_COMMAND_NEXT | 1,
		MUSIC_COMMAND_PLAY_NOTE | MUSIC_TRACK_0 | NOTE_A4,
		MUSIC_COMMAND_NEXT | 1,
		MUSIC_COMMAND_PLAY_NOTE | MUSIC_TRACK_0 | NOTE_B4,
		MUSIC_COMMAND_NEXT | 1,
		MUSIC_COMMAND_PLAY_NOTE | MUSIC_TRACK_0 | NOTE_C5,
		MUSIC_COMMAND_NEXT | 1,

		MUSIC_COMMAND_NEXT | 3,

		MUSIC_COMMAND_STOP
};

const uint16_t ohSusannaSong[] = {
		MUSIC_COMMAND_SPEED | 480,
		MUSIC_COMMAND_INSTRUMENT | MUSIC_TRACK_0 | INSTRUMENT_ELECTRIC_PIANO,
		MUSIC_COMMAND_VOLUME | MUSIC_TRACK_0 | 255,
//		MUSIC_COMMAND_DELAY | MUSIC_TRACK_2 | 16,
//		MUSIC_COMMAND_DELAY | MUSIC_TRACK_3 | 8,

		MUSIC_COMMAND_PLAY_NOTE | MUSIC_TRACK_0 | NOTE_C4,
		MUSIC_COMMAND_NEXT | 1,
		MUSIC_COMMAND_PLAY_NOTE | MUSIC_TRACK_0 | NOTE_D4,
		MUSIC_COMMAND_NEXT | 1,

		MUSIC_COMMAND_PLAY_NOTE | MUSIC_TRACK_0 | NOTE_E4,
		MUSIC_COMMAND_NEXT | 2,
		MUSIC_COMMAND_PLAY_NOTE | MUSIC_TRACK_0 | NOTE_G4,
		MUSIC_COMMAND_NEXT | 2,
		MUSIC_COMMAND_PLAY_NOTE | MUSIC_TRACK_0 | NOTE_G4,
		MUSIC_COMMAND_NEXT | 3,
		MUSIC_COMMAND_PLAY_NOTE | MUSIC_TRACK_0 | NOTE_A4,
		MUSIC_COMMAND_NEXT | 1,

		MUSIC_COMMAND_PLAY_NOTE | MUSIC_TRACK_0 | NOTE_G4,
		MUSIC_COMMAND_NEXT | 2,
		MUSIC_COMMAND_PLAY_NOTE | MUSIC_TRACK_0 | NOTE_E4,
		MUSIC_COMMAND_NEXT | 2,
		MUSIC_COMMAND_PLAY_NOTE | MUSIC_TRACK_0 | NOTE_C4,
		MUSIC_COMMAND_NEXT | 3,
		MUSIC_COMMAND_PLAY_NOTE | MUSIC_TRACK_0 | NOTE_D4,
		MUSIC_COMMAND_NEXT | 1,

		MUSIC_COMMAND_PLAY_NOTE | MUSIC_TRACK_0 | NOTE_E4,
		MUSIC_COMMAND_NEXT | 2,
		MUSIC_COMMAND_PLAY_NOTE | MUSIC_TRACK_0 | NOTE_E4,
		MUSIC_COMMAND_NEXT | 2,
		MUSIC_COMMAND_PLAY_NOTE | MUSIC_TRACK_0 | NOTE_D4,
		MUSIC_COMMAND_NEXT | 2,
		MUSIC_COMMAND_PLAY_NOTE | MUSIC_TRACK_0 | NOTE_C4,
		MUSIC_COMMAND_NEXT | 2,


		MUSIC_COMMAND_PLAY_NOTE | MUSIC_TRACK_0 | NOTE_D4,
		MUSIC_COMMAND_NEXT | 6,
		MUSIC_COMMAND_PLAY_NOTE | MUSIC_TRACK_0 | NOTE_C4,
		MUSIC_COMMAND_NEXT | 1,
		MUSIC_COMMAND_PLAY_NOTE | MUSIC_TRACK_0 | NOTE_D4,
		MUSIC_COMMAND_NEXT | 1,

		MUSIC_COMMAND_PLAY_NOTE | MUSIC_TRACK_0 | NOTE_E4,
		MUSIC_COMMAND_NEXT | 2,
		MUSIC_COMMAND_PLAY_NOTE | MUSIC_TRACK_0 | NOTE_G4,
		MUSIC_COMMAND_NEXT | 2,
		MUSIC_COMMAND_PLAY_NOTE | MUSIC_TRACK_0 | NOTE_G4,
		MUSIC_COMMAND_NEXT | 3,
		MUSIC_COMMAND_PLAY_NOTE | MUSIC_TRACK_0 | NOTE_A4,
		MUSIC_COMMAND_NEXT | 1,

		MUSIC_COMMAND_PLAY_NOTE | MUSIC_TRACK_0 | NOTE_G4,
		MUSIC_COMMAND_NEXT | 2,
		MUSIC_COMMAND_PLAY_NOTE | MUSIC_TRACK_0 | NOTE_E4,
		MUSIC_COMMAND_NEXT | 2,
		MUSIC_COMMAND_PLAY_NOTE | MUSIC_TRACK_0 | NOTE_C4,
		MUSIC_COMMAND_NEXT | 3,
		MUSIC_COMMAND_PLAY_NOTE | MUSIC_TRACK_0 | NOTE_D4,
		MUSIC_COMMAND_NEXT | 1,

		MUSIC_COMMAND_PLAY_NOTE | MUSIC_TRACK_0 | NOTE_E4,
		MUSIC_COMMAND_NEXT | 2,
		MUSIC_COMMAND_PLAY_NOTE | MUSIC_TRACK_0 | NOTE_E4,
		MUSIC_COMMAND_NEXT | 2,
		MUSIC_COMMAND_PLAY_NOTE | MUSIC_TRACK_0 | NOTE_D4,
		MUSIC_COMMAND_NEXT | 2,
		MUSIC_COMMAND_PLAY_NOTE | MUSIC_TRACK_0 | NOTE_D4,
		MUSIC_COMMAND_NEXT | 2,


		MUSIC_COMMAND_PLAY_NOTE | MUSIC_TRACK_0 | NOTE_C4,
		MUSIC_COMMAND_NEXT | 8,

		MUSIC_COMMAND_STOP
};
